### ISSUE TITLE
Subject charset issue

### ISSUE THREAD

**Issue by dokime7** [theruziev/async_sender#228]
Hi and thanks for this useful lib :)

I'm using 1.4.4 version

For improve deliverability it should be good to encode the message subject to utf-8 only when it contains no ascii char.
My issue is that Rspamd anti-spam add SUBJ_EXCESS_QP flag in this case and inscrease bad score.

See: [Rspamd rule](https://github.com/rspamd/rspamd/blob/c7bde491422159dc532c7d6c9934f350ba803c40/rules/regexp/headers.lua#L293)

Thanks

**Comment by theruziev** [comment]
I am glad to hear that. 

I will try to fix that, but I need code review. I assign it to you for review. 
I was read your other issue and will look too.

**Comment by dokime7** [comment]
Great!
If you want a quick implementation, I've submit a PR here for same issue:
https://github.com/caronc/apprise/pull/660/files#diff-a25a4da88bd4ee661599f260147d96e27fa3051b71ba4f4b88a87e5834cff3e8
just search for `_get_charset method` :)
