### ISSUE TITLE
Double Subject header (Critical)

### ISSUE THREAD

**Issue by bokolob** [theruziev/async_sender#246]
Hello.

It seems that here - https://github.com/theruziev/async_sender/issues/228 was added some fix, after which Message object can contain two Subject headers.

It's unacceptable for some SMPT servers, like GMAIL. They reject such messages as spam.

As fast fix I've added some unicode emoji to subject :)

**Comment by theruziev** [comment]
Got it, work on fix. @bokolob which version of library you use? Can I fix this on last major release?
